const ERROR_CODE = 400;
const ERROR_NOT_FOUND = 404;
const ERROR_DEFAULT = 500;
const ERROR_CONFLICT_VALUE = 409;
const ERROR_INCORRECT_TOKEN = 401;
const ERROR_FORBIDDEN_REQUEST = 403;

module.exports = {
  ERROR_CODE,
  ERROR_NOT_FOUND,
  ERROR_DEFAULT,
  ERROR_CONFLICT_VALUE,
  ERROR_INCORRECT_TOKEN,
  ERROR_FORBIDDEN_REQUEST,
};
